#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=28gb,walltime=3:00:00
#PBS -N app-AFQclean
#PBS -V

set -e
set -x

singularity exec -e docker://brainlife/mcr:r2019a ./compiled/afqcleantracts
if [ ! -s output.mat ]; then 
    exit 1
fi

echo "bypassing surfaces/"
surfaces=$(dirname `jq -r .afq_fg config.json`)/surfaces
if [ -d $surfaces ]; then
    cp -r $surfaces ./surfaces
fi
