#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=1:30:00
#PBS -N app-AFQclean
#PBS -V

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/afqcleantracts

if [ -s output.mat ]; 
then 
  exit 0
else
  echo "Cannot find file to run."
  exit 1
fi
